### PR TITLE
Fix overloaded virtual print in DirectedEdge*.

### PR DESCRIPTION
**Pull request by schwehr**
- Make print() method of child classes also const
- Make getDepthDelta() const
- Add virtual.  For C++11 and newer this eventually should be overload.

e.g.

geos::geomgraph::DirectedEdge::print' hides overloaded virtual function [-Woverloaded-virtual]

### CODE REVIEW

**Comment by mloskot** [comment]
@schwehr 
> For C++11 and newer this eventually should be overload.

You mean `override` (or `final`), don't you, Kurt?

**Comment by schwehr** [comment]
@mloskot , Yes, I meant `override`.  Sorry.

**Comment by mloskot** [comment]
@schwehr no problem. I'll try to merge it soon.

**Comment by strk** [comment]
Mat: please let's try to avoid complex history (ie: always rebase before merge)

**Comment by mloskot** [comment]
@strk Yes, `rebase` is the workflow I use.

**Comment by mloskot** [comment]
## IMPORTANT

Since [`svn-trunk` has been renamed to `master`](https://trac.osgeo.org/geos/ticket/822), I have rebased this PR against the current `master`. Hopefully, it won't break anything.

**Comment by dbaston** [comment]
Looks like this was already merged: https://github.com/OSGeo/geos/commit/6bb7b349a7c7a095565abfe4a4a7bd65c3c5d8ae

**Pull request closed without merging**
