### PR TITLE
[CMake] Simplify generation of geos_revision.h

### PR DESCRIPTION
**Pull request by mloskot**
Remove `tools/geos_revision_cmake.h.in` as no longer required - `geos_revision.h` is generated on-fly.

Add `geos_revision` target set as dependency of `geos_c` target.

### CODE REVIEW

**Comment by strk** [comment]
Remember to push in upstream, not here.
If you find a way, we should ideally *forbid* merging any PR with the button here (I suspect there's a way but don't want to pollute my brain into learning use of proprietary tools...)

**Comment by mloskot** [comment]
@strk 
> Remember to push in upstream, not here.

Yes, that's clear to me.

> we should ideally forbid merging any PR with the button here

I'll check that https://trac.osgeo.org/geos/ticket/823

**Comment by hobu** [comment]
> we should ideally forbid merging any PR with the button here

It's like you purposefully make it as hard as possible for people to contribute.

**Comment by strk** [comment]
On Sun, Apr 09, 2017 at 09:42:15PM -0700, Howard Butler wrote:
> > we should ideally forbid merging any PR with the button here
> 
> It's like you purposefully make it as hard as possible for people to contribute.

Contributing has never implied pushing a button.
It's just eventually harder for *mergers*

--strk;

**Pull request merged**
