### PR TITLE
Fix leaks: cleanup if failing to parse the WKT MultiLineString, MultiPolygon, and GeometryCollection string. (#830)

### PR DESCRIPTION
**Pull request by schwehr**
Wrap parsing in try blocks.
Catch any exception, cleanup, and rethrow.

Proposed solution for https://trac.osgeo.org/geos/ticket/830

### CODE REVIEW

**Comment by strk** [comment]
Please fix these:
```
WKTReader.cpp: In member function ‘geos::geom::MultiLineString* geos::io::WKTReader::readMultiLineStringText(geos::io::StringTokenizer*)’:
WKTReader.cpp:416:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i < lineStrings->size(); i++)
                   ^
WKTReader.cpp: In member function ‘geos::geom::MultiPolygon* geos::io::WKTReader::readMultiPolygonText(geos::io::StringTokenizer*)’:
WKTReader.cpp:446:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i < polygons->size(); i++)
                   ^
WKTReader.cpp: In member function ‘geos::geom::GeometryCollection* geos::io::WKTReader::readGeometryCollectionText(geos::io::StringTokenizer*)’:
WKTReader.cpp:476:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i < geoms->size(); i++)
                   ^
```

And provide a test showing the leak before the patch

PS: a "delete geom" line was not indented as the rest of the file

**Comment by schwehr** [comment]
My tests are here.  Sorry they are not done as a patch for libgeos.

https://github.com/schwehr/gdal-autotest2/commit/92f23e203c849d3919922cd04228d041a5917859

**Comment by strk** [comment]
Would you feel like adding those tests here too ?
tests/unit/io/WKTWriterTest.cpp

**Comment by schwehr** [comment]
Please take a look at the tests.

**Comment by strk** [comment]
Pushed as 84477476f382c4d40860879dfbbc96b6e1d16f39, thanks

**Pull request closed without merging**
